"""
Django settings for algo_trade project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

from dotenv import load_dotenv

import logging
import sentry_sdk
from sentry_sdk.integrations.celery import CeleryIntegration
from sentry_sdk.integrations.django import DjangoIntegration
from sentry_sdk.integrations.logging import LoggingIntegration
from sentry_sdk.integrations.redis import RedisIntegration

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-a8dt6pdb#x9n6ypw&iez#^wa)*#_n!hu+$oqihgcv82i+fv$@&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [ '0.0.0.0','127.0.0.1','localhost']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'algo.apps.AlgoConfig',
    '''django_celery_beat''',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'algo_trade.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'algo_trade.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_DATABASE', 'algo_db'),
        'USER': os.getenv('DB_USERNAME', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD', 'your_password'),
        # Change this line:
        'HOST': os.getenv('DB_HOST', 'postgres'),  # Use the service name 'postgres'
        'PORT': os.getenv('DB_PORT', 5432),
    }
}
# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# urls wallex
WALLEX_BASE_URL : str = os.getenv('WALLEX_BASE_URL', 'https://api.wallex.ir/')
WALLEX_ORDER_BOOK_PATH : str = os.getenv('WALLEX_ORDER_BOOK_PATH', 'v2/depth/all')
WALLEX_ORDER_BOOK_PATH_BY_SYMBOL : str = os.getenv('WALLEX_ORDER_BOOK_PATH_BY_SYMBOL', 'v1/depth?symbol=')
WALLEX_MARKET_PATH : str = os.getenv('WALLEX_MARKET_PATH', 'v1/markets')
WALLEX_ASSET_PATH : str = os.getenv('WALLEX_ASSET_PATH', 'v1/currencies')
WALLEX_ORDER_CREATE_PATH : str = os.getenv('WALLEX_ORDER_CREATE_PATH', 'v1/account/orders')
WALLEX_ACTIVE_ORDERS_PATH : str = os.getenv('WALLEX_ACTIVE_ORDERS_PATH', 'v1/account/openOrders')
WALLEX_ORDER_INFO_PATH : str = os.getenv('WALLEX_ORDER_INFO_PATH', 'v1/account/orders/')
WALLEX_CANCEL_ORDER_PATH : str = os.getenv('WALLEX_CANCEL_ORDER_PATH', 'v1/account/orders')
WALLEX_GET_BALANCES_PATH : str = os.getenv('WALLEX_GET_BALANCES_PATH', 'v1/account/balances/')
WALLEX_OHLCV_HISTORY_PATH : str = os.getenv('WALLEX_OHLCV_HISTORY_PATH',"v1/market/klines")

#url nobitex
NOBITEX_BASE_URL : str = os.getenv('NOBITEX_BASE_URL', 'https://apiv2.nobitex.ir/')
NOBITEX_ORDER_BOOK_PATH : str = os.getenv('NOBITEX_ORDER_BOOK_PATH', 'v2/depth/all')
NOBITEX_ORDER_BOOK_PATH_BY_SYMBOL : str = os.getenv('NOBITEX_ORDER_BOOK_PATH_BY_SYMBOL', '/v3/orderbook/')
NOBITEX_MARKET_PATH : str = os.getenv('NOBITEX_MARKET_PATH', 'v1/markets')
NOBITEX_ASSET_PATH : str = os.getenv('NOBITEX_ASSET_PATH', 'v1/currencies')

NOBITEX_ORDER_CREATE_PATH : str = os.getenv('NOBITEX_ORDER_CREATE_PATH', 'market/orders/add') # This is a POST endpoint, often a v2 path.
NOBITEX_ACTIVE_ORDERS_PATH : str = os.getenv('NOBITEX_ACTIVE_ORDERS_PATH', 'v1/account/openOrders') # This is a GET endpoint.
NOBITEX_ORDER_INFO_PATH : str = os.getenv('NOBITEX_ORDER_INFO_PATH', 'v1/market/orders/status') # This is a POST endpoint.
NOBITEX_CANCEL_ORDER_PATH : str = os.getenv('NOBITEX_CANCEL_ORDER_PATH', 'v1/market/orders/update-status') # This is a POST endpoint.
NOBITEX_GET_BALANCES_PATH : str = os.getenv('NOBITEX_GET_BALANCES_PATH', 'users/wallets/balance') # This is a POST endpoint.
NOBITEX_OHLCV_HISTORY_PATH : str = os.getenv('NOBITEX_OHLCV_HISTORY_PATH', "market/udf/history")
NOBITEX_STOP_LOOSE_PATH : str = os.getenv('NOBITEX_STOP_LOOSE_PATH', '/market/orders/add') # This is a POST endpoint.

#log prefix
STRATEGY_PROCESSOR_LOG_PREFIX = 'PROCESSOR => '
DEAL_PROCESSING_LOG_PREFIX = 'DEAL_PROCESSOR => '
ORDER_MANAGEMENT_LOG_PREFIX = 'ORDER_MGMT => '
CANCEL_ORDER_LOG_PREFIX = 'ORDER_CANCEL => '
INQUIRY_ORDER_LOG_PREFIX = 'INQUIRY => '
BALANCE_ORDER_LOG_PREFIX = 'BALANCE => '
LOG_CANCEL_PREFIX = 'CANCEL => '
ASSET_LOG_PREFIX = 'ASSET => '
MARKET_DATA_LOG_PREFIX = 'MARKET =>'
STOP_ORDER_MONITOR_LOG_PREFIX = 'STOP_MONITOR => '

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@algo-trade.com')

#redis config
REDIS_HOST = os.getenv('REDIS_HOST', 'redis')
REDIS_PORT : int = int(os.getenv('REDIS_PORT', '6379'))
REDIS_DB : int = int(os.getenv('REDIS_DB', 0))


# Celery settings
CELERY_BROKER_URL = f"redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}"
CELERY_RESULT_BACKEND = f"redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}"
CELERY_TASK_RESULT_EXPIRES = int(os.getenv("CELERY_TASK_RESULT_EXPIRES", 60))
CELERY_WORKER_LOG_FORMAT = "CELERY-LOG =>  %(asctime)s [%(levelname)s] %(name)s: %(message)s"
CELERY_WORKER_TASK_LOG_FORMAT = "CELERY-LOG =>  %(asctime)s [%(levelname)s] %(name)s: %(message)s"
CELERY_BEAT_LOG_FORMAT = "CELERY-LOG =>  %(asctime)s [%(levelname)s] %(name)s: %(message)s"
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"
CELERY_WORKER_SEND_TASK_EVENTS = True
CELERY_TASK_SEND_SENT_EVENT = True
CELERY_TASK_TIME_LIMIT = 300

#Logging and Sentry settings
LOGGING = {
    "version": 1,
    "disable_existing_loggers": True,
    "formatters": {
        "verbose": {
            "format": "%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s",
        },
    },
    "handlers": {
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {"level": "INFO", "handlers": ["console"]},
    "loggers": {
        "django.db.backends": {
            "level": "ERROR",
            "handlers": ["console"],
            "propagate": False,
        },
        # Errors logged by the SDK itself
        "sentry_sdk": {"level": "ERROR", "handlers": ["console"], "propagate": False},
        "django.security.DisallowedHost": {
            "level": "ERROR",
            "handlers": ["console"],
            "propagate": False,
        },
    },
}
SENTRY_DSN = os.getenv("SENTRY_DSN", "")
SENTRY_LOG_LEVEL = int(os.getenv("DJANGO_SENTRY_LOG_LEVEL", logging.INFO))

sentry_logging = LoggingIntegration(
    level=SENTRY_LOG_LEVEL,  # Capture info and above as breadcrumbs
    event_level=logging.ERROR,  # Send errors as events
)

integrations = [
    sentry_logging,
    DjangoIntegration(),
    CeleryIntegration(),
    RedisIntegration(),
]

SENTRY_ENVIRONMENT = os.getenv("SENTRY_ENVIRONMENT", "staging")

sentry_sdk.init(
    dsn=SENTRY_DSN,
    integrations=integrations,
    environment=os.getenv("SENTRY_ENVIRONMENT", default="production"),
    traces_sample_rate=float(os.getenv("SENTRY_TRACES_SAMPLE_RATE", default=1.0)),
    profiles_sample_rate=float(os.getenv("SENTRY_PROFILES_SAMPLE_RATE", default=1.0)),
)
