# Generated by Django 4.2.16 on 2025-08-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='step_size',
            field=models.FloatField(default=1.0, help_text='The step size for volume adjustments.'),
        ),
        migrations.AlterField(
            model_name='market',
            name='tick_size',
            field=models.FloatField(default=1.0, help_text='The step size for price adjustments.'),
        ),
        migrations.AlterUniqueTogether(
            name='market',
            unique_together={('symbol', 'provider')},
        ),
    ]
