# Generated by Django 4.2.16 on 2025-09-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0002_alter_market_step_size_alter_market_tick_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='provider',
            field=models.CharField(choices=[('Wallex', 'WALLEX')], default='Wallex', help_text='The provider type for this client.', max_length=50),
        ),
        migrations.AlterField(
            model_name='market',
            name='provider',
            field=models.CharField(choices=[('Wallex', 'WALLEX')], default='Wallex', help_text='The provider type for this client.', max_length=50),
        ),
        migrations.AlterField(
            model_name='storeclient',
            name='provider',
            field=models.CharField(choices=[('Wallex', 'WALLEX')], default='Wallex', help_text='The provider type for this client.', max_length=50),
        ),
    ]
