# Generated by Django 4.2.16 on 2025-09-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0003_alter_asset_provider_alter_market_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategyconfig',
            name='initial_history_period_days',
            field=models.IntegerField(default=90, help_text='Number of days of historical data to fetch for indicator calculations'),
        ),
    ]
