# Generated by Django 4.2.16 on 2025-09-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0004_alter_strategyconfig_initial_history_period_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategyconfig',
            name='strategy',
            field=models.CharField(choices=[('BreakoutStrategy', 'BreakoutStrategy'), ('StrategyMacdEmaCross', 'StrategyMacdEmaCross')], default='StrategyMacdEmaCross', max_length=255),
        ),
    ]
