# Generated by Django 4.2.16 on 2025-09-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0005_alter_strategyconfig_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='stop_loss_order_id',
            field=models.CharField(blank=True, help_text='Exchange order ID for stop-loss order', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='stop_loss_price',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Stop-loss price for automatic exit', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='take_profit_order_id',
            field=models.CharField(blank=True, help_text='Exchange order ID for take-profit order', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='take_profit_price',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Take-profit price for automatic exit', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='trailing_stop_distance',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Trailing stop distance percentage', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='trailing_stop_enabled',
            field=models.BooleanField(default=False, help_text='Whether trailing stop is enabled'),
        ),
    ]
