# Generated by Django 4.2.16 on 2025-09-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0006_deal_stop_loss_order_id_deal_stop_loss_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsystemconfig',
            name='admin_email',
            field=models.EmailField(default='shokoohrigi22@gmail.com', help_text='Admin email address for receiving notifications.', max_length=254),
        ),
        migrations.AddField(
            model_name='adminsystemconfig',
            name='email_host',
            field=models.CharField(default='smtp.gmail.com', help_text='SMTP server host for sending emails.', max_length=255),
        ),
        migrations.AddField(
            model_name='adminsystemconfig',
            name='email_host_password',
            field=models.CharField(blank=True, help_text='SMTP password for authentication.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adminsystemconfig',
            name='email_host_user',
            field=models.EmailField(blank=True, help_text='SMTP username for authentication.', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='adminsystemconfig',
            name='email_notifications_enabled',
            field=models.BooleanField(default=True, help_text='Enable email notifications for trading events.'),
        ),
        migrations.AddField(
            model_name='adminsystemconfig',
            name='email_port',
            field=models.PositiveIntegerField(default=587, help_text='SMTP server port for sending emails.'),
        ),
        migrations.AddField(
            model_name='adminsystemconfig',
            name='email_use_tls',
            field=models.BooleanField(default=True, help_text='Use TLS for email connection.'),
        ),
        migrations.AddField(
            model_name='adminsystemconfig',
            name='from_email',
            field=models.EmailField(default='noreply@algo-trade.com', help_text='From email address for sending notifications.', max_length=254),
        ),
    ]
